### ISSUE TITLE
Problems with Xcode 7.3 Swift 2.2

### ISSUE THREAD

**Issue by AndrewPetrov** [jpsim/PeerKit#19]
I've just created new project and imported there PeerKit via "pod install". This is what I've got https://www.dropbox.com/s/nsbavu537rkro3m/Screenshot%202016-05-02%2011.21.15.png?dl=0
26 errors caused by deprecated syntax (for example line 23 on the screenshot). What I'm doing wrong? How to install this lib correctly?

**Comment by jpsim** [comment]
The reason that wouldn't work is that you're not using the latest version of PeerKit from source. The last CocoaPods version I pushed up was prior to Swift 2 support. I just pushed version 2.0.0 up, so you could now just use that.
