### ISSUE TITLE
Feature Request - OS X Support

### ISSUE THREAD

**Issue by vinkla** [jpsim/PeerKit#2]
This would be an great feature. Maybe this is possible already?

**Comment by jpsim** [comment]
Good idea! I just added shared iOS and OSX schemes in the [swift1p2](https://github.com/jpsim/PeerKit/tree/swift1p2) branch. Let me know if you need help setting it up. Note that you'll need Xcode 6.3 Beta 3 to build that branch.

**Comment by vinkla** [comment]
Great, thanks!
