### ISSUE TITLE
Any update for support Swift 3

### ISSUE THREAD

**Issue by harryhow** [jpsim/PeerKit#22]
Hi 

I'm trying to convert your project into Swift 3 with XCode 8.1 beta, but it failed to convert.

Any leads to solve this issue or plan to support Swift 3?

Thanks!

**Comment by harryhow** [comment]
Sorry, i want to correct my question, I saw you already supporting SWIFT3, but it seems not in Pod?

**Comment by jpsim** [comment]
I just pushed [3.0.0](https://github.com/jpsim/PeerKit/releases/tag/3.0.0) as a tag and to CocoaPods trunk: https://github.com/CocoaPods/Specs/commit/be1bb15e470d42d6d04eb8e33ac24d613a1e874b

**Comment by harryhow** [comment]
@jpsim Thanks for updating PeerKit in Pods, however I still met issues after converting to SWIFT 3.0.

I assume Xcode won't remind me to convert to Swift 3.0 after I've updated with PeerKit Pod 3.0.0.
But when I open .xcworkspace after Pod install, Xcode still ask me if I want to convert to Swift 3.0.
After converting, bunch of errors happen. Any leads to solve this issue? 

<img width="1393" alt="screen shot 2016-11-12 at 6 11 15 pm" src="https://cloud.githubusercontent.com/assets/693098/20237085/75dea8be-a903-11e6-8d42-3b1418e79ece.png">

**Comment by jpsim** [comment]
Update CocoaPods
