### ISSUE TITLE
Support of swift 4

### ISSUE THREAD

**Issue by ooii** [jpsim/PeerKit#26]
Hi,

Is a swift 4 version in the pipes? 
Thanks.

**Comment by jpsim** [comment]
Done: https://github.com/jpsim/PeerKit/releases/tag/4.0.0

**Comment by ooii** [comment]
Thanks.
Any idea if it's coming to pod? If yes, any EAT?

**Comment by jpsim** [comment]
Just pushed: https://github.com/CocoaPods/Specs/commit/1878426dfa4d0ad6b250b8877d891446955a2338

**Comment by ooii** [comment]
Very well. Thanks for the third time this evening.
