### ISSUE TITLE
Distribute through CocoaPods

### ISSUE THREAD

**Issue by nickswalker** [jpsim/PeerKit#5]
Would you be amenable to distributing PeerKit through CocoaPods? I'm sure this would make many people's lives a little easier. The [process](http://guides.cocoapods.org/making/specs-and-specs-repo.html) isn't too involved.

**Comment by jpsim** [comment]
Can you add a PR containing a Podspec? I'd be happy to merge in.

**Comment by nickswalker** [comment]
@jpsim Bump
